2025 week 37 update

diff --git a/docs/recipes/k8s/cloud/deploy-tp-aro.yaml b/docs/recipes/k8s/cloud/deploy-tp-aro.yaml
--- a/docs/recipes/k8s/cloud/deploy-tp-aro.yaml
+++ b/docs/recipes/k8s/cloud/deploy-tp-aro.yaml
@@ -85,6 +85,7 @@ meta:
     TP_CREATE_ARO_CLUSTER: ${GUI_TP_CREATE_ARO_CLUSTER:-true}
     TP_GET_SETUP_DETAILS: ${GUI_TP_GET_SETUP_DETAILS:-true}
     TP_INSTALL_STORAGE_CLASS_POSTGRES: ${GUI_TP_INSTALL_STORAGE_CLASS_POSTGRES:-true}
+    TP_INSTALL_MAILDEV: ${GUI_TP_INSTALL_MAILDEV:-true}
     TP_CLEAN_UP_SCRIPT_FILENAME: clean-up.sh
     TP_CLEAN_UP: ${GUI_TP_CLEAN_UP:-false}
 tasks:
@@ -463,6 +464,55 @@ tasks:
                 memory: 256Mi
         EOF
         helm repo remove postgresql
+        kubectl label namespace tibco-ext networking.platform.tibco.com/non-dp-ns=enable
+        kubectl label namespace tibco-ext networking.platform.tibco.com/non-cp-ns=enable
+  - condition: ${TP_INSTALL_MAILDEV}
+    script:
+      ignoreErrors: false
+      content: |
+        uname=$(az aro list-credentials --name ${TP_CLUSTER_NAME} --resource-group ${TP_RESOURCE_GROUP} --query kubeadminUsername -otsv)
+        password=$(az aro list-credentials --name ${TP_CLUSTER_NAME} --resource-group ${TP_RESOURCE_GROUP} --query kubeadminPassword -otsv)
+        apiServer=$(az aro show -g ${TP_RESOURCE_GROUP} -n ${TP_CLUSTER_NAME} --query apiserverProfile.url -o tsv)
+        oc login ${apiServer} -u ${uname} -p ${password}
+        _return_code=$?
+        if [[ $_return_code -ne 0 ]]; then
+          echo "Login failed with error code: $_return_code due to issue"
+          echo "Insecure login"
+          oc login ${apiServer} -u ${uname} -p ${password} --insecure-skip-tls-verify=true
+        fi
+        helm upgrade --install --wait --timeout 1h --debug maildev generic-chart --repo https://test-server.github.yyzd.me -n tibco-ext --version "^1.0.0" --labels layer=2 --create-namespace -f - << EOF
+        deployment:
+          enabled: true
+          image:
+            repository: maildev/maildev
+            tag: latest
+          args: ["-s", "1025", "-w", "1080"]
+          ports:
+            http:
+              enabled: true
+              protocol: TCP
+              containerPort: 1080
+          podLabels:
+            app: maildev
+        service:
+          enabled: true
+          name: development-mailserver
+          ports:
+            http:
+              enabled: true
+              protocol: TCP
+              containerPort: 1080
+              servicePort: 1080
+            smtp:
+              enabled: true
+              protocol: TCP
+              containerPort: 1025
+              servicePort: 1025
+        ingress:
+          enabled: false
+        EOF
+        kubectl label namespace tibco-ext networking.platform.tibco.com/non-dp-ns=enable
+        kubectl label namespace tibco-ext networking.platform.tibco.com/non-cp-ns=enable
   - condition: ${INSTALL_ARO_CP}
     script:
       ignoreErrors: false
